---

version: '2.3'
services:
  redis:
    image: redis:5.0
    restart: always
    networks: 
      - compose_net
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_DB: feed
      POSTGRES_USER: feed
      POSTGRES_PASSWORD: feed
    networks: 
      - compose_net
    volumes:
      - postgres-data:/var/lib/postgresql/data      
    ports:
      - "5432:5432"
  app:
    build:
      context: ./app
    image: app_image
    restart: always
    depends_on:
      - redis
      - db
    environment:
      REDIS_ADDRESS: redis://redis:6379
      POSTGRES_ADDRESS: postgres://feed:feed@db:5432/feed?sslmode=disable
      RSS_URL: https://hackernoon.com/feed
      LOG_LEVEL: INFO
    networks: 
      - compose_net
    ports:
      - "8080:8080"
  app_exporter:
    image: registry.gitlab.com/tfs18f-ekb-devops/student/a.kazarjan/app-exporter:latest
    restart: always
    depends_on:
      - app
    networks:
      - compose_net
    ports:
      - "7777:7777"
  blackbox_exporter:
    image: prom/blackbox-exporter:v0.12.0
    restart: always
    networks:
      - compose_net
    ports:
      - "9115:9115"
  node_exporter:
    image: prom/node-exporter:v0.16.0
    restart: always
    networks:
      - compose_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
  postgres_exporter:
    image: wrouesnel/postgres_exporter:v0.4.7
    restart: on-failure
    command:
      - --extend.query-path=/etc/postgres_exporter/queries.yml
    depends_on:
      - db
    networks:
      - compose_net
    volumes:
      - ./config/postgres_queries.yml:/etc/postgres_exporter/queries.yml
    environment:
      DATA_SOURCE_NAME: postgres://feed:feed@db:5432/feed?sslmode=disable
    ports:
      - "9187:9187"
  redis_exporter:
    image: oliver006/redis_exporter:v0.22.1
    restart: on-failure
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis://redis:6379
    networks:
      - compose_net
    ports:
      - "9121:9121"
  alertmanager:
    image: prom/alertmanager:v0.15.3
    restart: on-failure
    networks:
      - compose_net
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
  prometheus:
    image: prom/prometheus:v2.5.0
    restart: on-failure
    depends_on:
      - postgres_exporter
      - redis_exporter
    networks:
      - compose_net
    volumes:
      - ./config/:/etc/prometheus/
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:5.3.4
    depends_on:
      - prometheus
    networks:
      - compose_net
    volumes:
      - ./grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"
networks:
  compose_net:
    driver: bridge
volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local