stages:
- lint
- build

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/app_image

yamllint:
  stage: lint
  image: sdesbure/yamllint
  script:
    - yamllint docker_compose/ playbooks/

ansible_linting:
  stage: lint
  image: sdesbure/ansible-lint
  script:
    - ansible-lint playbooks/*.yml -x ANSIBLE0012,ANSIBLE0006

build_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/tfs18f-ekb-devops/public/application.git docker_compose/app/application
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_IMAGE:latest ./docker_compose/app
    - docker push $CONTAINER_IMAGE:latest

