{
 "title": "App Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App Server RPM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_metric_server_request_counter[1m]) * 60"
    }
   ]
  },
  {
   "title": "App Server Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_metric_server_error_counter / app_metric_server_request_counter"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_metric_worker_items_total" }
   ]
  },
  {
   "title": "Fetch duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_metric_worker_fetch_duration_seconds"
    }
   ]
  },
  {
   "title": "Fetch Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_metric_worker_fetch_failure_counter[1m]) / \n(rate(app_metric_worker_fetch_success_counter[1m]) + rate(app_metric_worker_fetch_failure_counter[1m]))"
    }
   ]
  },
  {
   "title": "Database Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_metric_worker_db_errors_counter"
    }
   ]
  }
 ]
}