---

- name: Docker playbook
  hosts: localhost
  pre_tasks:
    - name: Install Docker Python library.
      pip: name=docker state=present
  tasks:
    - name: Build images
      docker_image:
        name: "{{ item.name }}"
        path: "{{ item.directory }}"
        state: build
      with_items:
        - { name: db_image, directory: db }
        - { name: redis_image, directory: redis }
        - { name: app_image, directory: app }

    - name: Create network
      docker_network:
        name: app_net

    - name: "Deploy services"
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        ports: ["{{ item.ports }}"]
        state: started
        auto_remove: true
        networks:
          - name: app_net
      with_items:
        - { name: db, image: db_image, ports: "5432:5432" }
        - { name: redis, image: redis_image, ports: "6379:6379" }
        - { name: app, image: app_image, ports: "8080:8080" }
