global:
  smtp_smarthost: 'smtp.yandex.ru:465'
  smtp_from: <from>
  smtp_auth_username: <username>
  smtp_auth_password: <secret>

route:
  group_by:
    - alertname
  receiver: "email" 

receivers:
  - name: "email"
    email_configs:
      - to: <secret>
        require_tls: false
