global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'blackbox_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['blackbox_exporter:9115']

  - job_name: 'blackbox_probe'
    metrics_path: /probe
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
